apiVersion: v1
kind: PersistentVolume
metadata:
  name: dwk-1-11-pv
spec:
  storageClassName: dwk-local-1-11
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /tmp/kube-dwk-1-11
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3s-default-server-0
